<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Mr_uniform-id_gender1</name>
   <tag></tag>
   <elementGuidId>bbd9846b-5587-4ceb-af00-4f5972017349</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uniform-id_gender1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='uniform-id_gender1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3cb4067d-1b3a-4070-863e-b664c7cf4e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>8900fd92-62cc-446f-81e0-292085355750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>1d4f60a2-f5a7-4e4c-82c7-ce640b8aa96c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uniform-id_gender1</value>
      <webElementGuid>1653723c-c984-41f8-966a-3bd17dcc1734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uniform-id_gender1&quot;)</value>
      <webElementGuid>a0ce3b1e-6563-4c76-8569-2b9f73608d14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='uniform-id_gender1']</value>
      <webElementGuid>df386e71-b8dc-4811-bcfa-8ff189ff6d91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='form']/div/div/div/div/form/div/div/label/div</value>
      <webElementGuid>d1a5f829-3c19-44d4-9e2d-727aac1e496a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title'])[1]/following::div[2]</value>
      <webElementGuid>d20606bf-2238-44c0-a028-33e6723d7895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div</value>
      <webElementGuid>c4d077b1-944d-4a24-94f3-180607e495e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'uniform-id_gender1']</value>
      <webElementGuid>160f3884-9f68-44bf-83d1-bb2bf8cf924a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
