<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__city</name>
   <tag></tag>
   <elementGuidId>eb9c3268-697c-47e9-83e2-194525c0a22f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#city</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='city']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>403ad347-a744-44b3-b80f-cb2ee581d5be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>06acdac6-608c-44db-9ae4-3c1276838383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>34c1f9d1-c298-465b-b357-f2d40f01e00d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4595eb56-ff94-4668-9634-6da77d6e7b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>4ec8ff38-1b44-4bd0-993a-d49c5d6a5924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>d4288adb-59e8-4c26-9e2b-13c80d5e21e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;city&quot;)</value>
      <webElementGuid>93418b64-a5f1-42c7-a0b0-0b6597425916</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='city']</value>
      <webElementGuid>9fb87c29-9b8d-4af4-b3b1-d6843a3ba663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='form']/div/div/div/div/form/p[8]/input</value>
      <webElementGuid>c5e23d2b-139c-4de6-ae87-97e23bdd53e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[8]/input</value>
      <webElementGuid>c15995d1-3655-440a-9516-30083ef1f3f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'city' and @id = 'city']</value>
      <webElementGuid>793b8335-c736-4616-aa73-b4985fd1b8bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
